### ISSUE TITLE
现在不能用了？

### ISSUE THREAD

**Issue by dihambo** [kafkalm/pcr-calculator#1]
我看那个parse_map文件里好像是找的\<tr\>\<td\>,但是我在哪个html文件里找不到了。。。

**Comment by kafkalm** [comment]
是哪个html文件？

**Comment by kafkalm** [comment]
> 我看那个parse_map文件里好像是找的<tr><td>,但是我在哪个html文件里找不到了。。。

是哪个html文件？我这边是可以使用的

**Comment by dihambo** [comment]
解析设计图

**Comment by kafkalm** [comment]
> 解析设计图

刚刚修复了下解析设计图的bug 你再pull下试试看？

**Comment by dihambo** [comment]
好的，麻烦了

**Comment by dihambo** [comment]
可以运行了。。另外这个是不是还没有匹配国服？
我看着不管是效率还是装备，都是日服的好像

**Comment by kafkalm** [comment]
> 可以运行了。。另外这个是不是还没有匹配国服？
> 我看着不管是效率还是装备，都是日服的好像

所有服都可以。国服的话，在图书馆配置角色的时候要设置rank上限；或者你直接在我这个计算器的“关卡限制”上，填上国服最新的关卡（比如9-14）。

**Comment by dihambo** [comment]
![QQ截图20200427202250](https://user-images.githubusercontent.com/35786546/80371809-13c78880-88c5-11ea-8940-5df182604441.png)
这个是我选择的，0次是什么意思呀？后边选择装备的时候，显示出来的也都是国服目前没有出的图
![QQ截图20200427202645](https://user-images.githubusercontent.com/35786546/80372054-791b7980-88c5-11ea-821a-d223fc9ea134.png)

**Comment by kafkalm** [comment]
> ![QQ截图20200427202250](https://user-images.githubusercontent.com/35786546/80371809-13c78880-88c5-11ea-8940-5df182604441.png)
> 这个是我选择的，0次是什么意思呀？后边选择装备的时候，显示出来的也都是国服目前没有出的图
> ![QQ截图20200427202645](https://user-images.githubusercontent.com/35786546/80372054-791b7980-88c5-11ea-821a-d223fc9ea134.png)

选择地图掉落模式的时候，把“每页显示”选择成全部，这样保存下来的地图掉落才是全的。你应该没有下全地图掉落。

**Comment by kafkalm** [comment]
> 可以运行了。。另外这个是不是还没有匹配国服？
> 我看着不管是效率还是装备，都是日服的好像

最好是直接在图书馆里配置好角色的rank上限，在地图掉落模式中选择好地图上限，可以提升计算器的效率。

**Comment by dihambo** [comment]
ok，可以了，就是没有显示银装哈哈，辛苦了大佬

**Comment by kafkalm** [comment]
> ok，可以了，就是没有显示银装哈哈，辛苦了大佬

图书馆设计图模式里有显示银装的选项，你点了就可以算银装了
