### ISSUE TITLE
将网页保存到本地（注意重命名) 疑问

### ISSUE THREAD

**Issue by adore595** [kafkalm/pcr-calculator#2]
想知道保存网页到本地这一步是保存为什么格式
![image](https://user-images.githubusercontent.com/28224318/80709399-cbf06d80-8b1f-11ea-9e3b-ae61e0d205d0.png)

我三种都试了下，gui运行之后一直提示错误

**Comment by kafkalm** [comment]
> 想知道保存网页到本地这一步是保存为什么格式
> ![image](https://user-images.githubusercontent.com/28224318/80709399-cbf06d80-8b1f-11ea-9e3b-ae61e0d205d0.png)
> 
> 我三种都试了下，gui运行之后一直提示错误

网页，全部。保存完后会有一个文件夹+一个html文件。比如先保存设计图模式，把这个html文件命名为设计图.html，然后保存地图掉落模式，命名为地图掉落.html，在选择栏里选择这两个HTML文件就行了。

**Comment by adore595** [comment]
好的谢谢拉
